spring.application.name=productService

server.port=8082

# ===============================
# KAFKA (Docker)
# ===============================
spring.kafka.producer.bootstrap-servers=kafka:9092
spring.kafka.consumer.bootstrap-servers=kafka:9092

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.group-id=product-events
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# ===============================
# DATABASE (Docker)
# ===============================
spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/shiroyadb
spring.datasource.username=postgres
spring.datasource.password=shiroya
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# ZIPKIN (Docker)
# ===============================
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

# ===============================
# LOGGING
# ===============================
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]