spring.application.name=productService

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/shiroyadb
spring.datasource.username=postgres
spring.datasource.password=shiroya
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

